name: Destroy the VPC infrastructure
run-name: Destroy VPC
on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow on PRs targeting 'main'

jobs:
  terraform-destroy:
    name: Destroy AWS VPC Infrastructure
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        terraform_version: 1.10.3

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy
